# coding => utf-8

require 'rbslicer/exceptions'

module HelperHandlerExceptions
  SLICER_EXCEPTIONS = {
    10 => Exceptions::AuthMissingHeaderException,
    11 => Exceptions::AuthAPIKeyException,
    12 => Exceptions::AuthInvalidAPIKeyException,
    13 => Exceptions::AuthIncorrectPermissionException,
    14 => Exceptions::AuthInvalidRemoteException,
    16 => Exceptions::CustomKeyInvalidPermissionForFieldException,
    17 => Exceptions::CustomKeyInvalidOperationException,
    18 => Exceptions::CustomKeyNotPermittedException,
    19 => Exceptions::CustomKeyRouteNotPermittedException,
    # Request validations (20 - 29)
    21 => Exceptions::RequestMissingContentTypeException,
    22 => Exceptions::RequestIncorrectContentTypeValueException,
    23 => Exceptions::RequestRateLimitException,
    24 => Exceptions::RequestInvalidJsonException,
    # Account Errors (30 - 39)
    30 => Exceptions::AccountMissingPaymentMethodException,
    31 => Exceptions::AccountPaymentRequiredException,
    32 => Exceptions::AccountBannedException,
    33 => Exceptions::AccountDisabledException,
    # Field errors (40 - 59)
    40 => Exceptions::FieldMissingParamException,
    41 => Exceptions::FieldTypeException,
    42 => Exceptions::FieldIntegerValuesException,
    43 => Exceptions::FieldAlreadyExistsException,
    44 => Exceptions::FieldLimitException,
    45 => Exceptions::FieldTimeSeriesLimitException,
    46 => Exceptions::FieldTimeSeriesSystemLimitException,
    47 => Exceptions::FieldDecimalTypeException,
    48 => Exceptions::FieldStorageValueException,
    49 => Exceptions::FieldInvalidApiNameException,
    50 => Exceptions::FieldInvalidNameException,
    51 => Exceptions::FieldInvalidDescriptionException,
    53 => Exceptions::FieldInvalidCardinalityException,
    54 => Exceptions::FieldDecimalLimitException,
    55 => Exceptions::FieldRangeLimitException,
    # Index errors (60 - 79)
    60 => Exceptions::IndexEntityKeyTypeException,
    61 => Exceptions::IndexEntityValueTypeException,
    62 => Exceptions::IndexFieldNameTypeException,
    63 => Exceptions::IndexFieldTypeException,
    64 => Exceptions::IndexEntityNameTooBigException,
    65 => Exceptions::IndexFieldValueTooBigException,
    66 => Exceptions::IndexDateFormatException,
    67 => Exceptions::IndexFieldNotActiveException,
    68 => Exceptions::IndexIdLimitException,
    69 => Exceptions::IndexFieldLimitException,
    71 => Exceptions::IndexFieldStringEmptyValueException,
    72 => Exceptions::IndexFieldTimeseriesInvalidParameterException,
    73 => Exceptions::IndexFieldNumericInvalidValueException,
    74 => Exceptions::IndexFieldTimeseriesMissingValueException,
    75 => Exceptions::QueryTimeSeriesInvalidPrecisionSecondsException,
    76 => Exceptions::QueryTimeSeriesInvalidPrecisionMinutesException,
    77 => Exceptions::QueryTimeSeriesInvalidPrecisionHoursException,
    # Query errors (80 - 109)
    80 => Exceptions::QueryMissingQueryException,
    81 => Exceptions::QueryInvalidTypeException,
    82 => Exceptions::QueryMissingTypeParamException,
    83 => Exceptions::QueryInvalidOperatorException,
    84 => Exceptions::QueryIncorrectOperatorUsageException,
    85 => Exceptions::QueryFieldNotActiveException,
    86 => Exceptions::QueryMissingOperatorException,
    87 => Exceptions::QueryIncompleteException,
    88 => Exceptions::QueryEventCountQueryException,
    89 => Exceptions::QueryDateFormatException,
    90 => Exceptions::QueryIntegerException,
    91 => Exceptions::QueryFieldLimitException,
    92 => Exceptions::QueryLevelLimitException,
    93 => Exceptions::QueryBadAggsFormationException,
    94 => Exceptions::QueryInvalidAggFilterException,
    95 => Exceptions::QueryMetricsLevelException,
    96 => Exceptions::QueryTimeSeriesException,
    97 => Exceptions::QueryMetricsTypeException,
    98 => Exceptions::QueryContainsNumericException,
    99 => Exceptions::QueryExistsEntityLimitException,
    100 => Exceptions::QueryMultipleFiltersException,
    101 => Exceptions::QueryContainsValueTypeException,
    102 => Exceptions::QueryMissingNameParamException,
    103 => Exceptions::QuerySavedAlreadyExistsException,
    104 => Exceptions::QuerySavedNotExistsException,
    105 => Exceptions::QuerySavedInvalidTypeException,
    106 => Exceptions::MethodNotAllowedException,
    107 => Exceptions::QueryExistsMissingIdsException,
    108 => Exceptions::QueryInvalidFormatException,
    109 => Exceptions::QueryTopValuesParameterEmptyException,
    110 => Exceptions::QueryDataExtractionLimitValueException,
    111 => Exceptions::QueryDataExtractionLimitValueTooBigException,
    112 => Exceptions::QueryDataExtractionLimitAndPageTokenValueException,
    113 => Exceptions::QueryDataExtractionPageTokenValueException,
    114 => Exceptions::QueryDataExtractionFieldLimitException,
    115 => Exceptions::QueryExistsEntityEmptyException,
    116 => Exceptions::QuerySavedInvalidQueryValueException,
    117 => Exceptions::QuerySavedInvalidCachePeriodValueException,
    118 => Exceptions::QuerySavedInvalidNameException,
    119 => Exceptions::QueryCountInvalidParameterErrorException,
    120 => Exceptions::QueryAggregationInvalidParameterException,
    121 => Exceptions::QueryAggregationInvalidFilterQueryException,
    # Internal errors (110 - 120)
    130 => Exceptions::InternalServerException,
    131 => Exceptions::FieldCreateInternalException
}
end
