# coding => utf-8

require 'rbslicer/exceptions'

module HelperHandlerExceptions
  SLICER_EXCEPTIONS = {
    10 => Exceptions::AuthMissingHeaderException,
    11 => Exceptions::AuthAPIKeyException,
    12 => Exceptions::AuthInvalidAPIKeyException,
    13 => Exceptions::AuthIncorrectPermissionException,
    14 => Exceptions::AuthInvalidRemoteException,
    15 => Exceptions::CustomKeyInvalidColumnCreationException,
    16 => Exceptions::CustomKeyInvalidPermissionForColumnException,
    17 => Exceptions::CustomKeyInvalidOperationException,
    18 => Exceptions::CustomKeyNotPermittedException,
    19 => Exceptions::CustomKeyRouteNotPermittedException,
    20 => Exceptions::DemoApiInvalidEndpointException,
    # Request validations (21 - 29)
    21 => Exceptions::RequestMissingContentTypeException,
    22 => Exceptions::RequestIncorrectContentTypeValueException,
    23 => Exceptions::RequestRateLimitException,
    24 => Exceptions::RequestInvalidJsonException,
    25 => Exceptions::RequestInvalidHttpMethodException,
    26 => Exceptions::RequestInvalidEndpointException,
    27 => Exceptions::RequestIncorrectHttpException,
    28 => Exceptions::RequestExceededLimitException,
    # Account Errors (30 - 39)
    30 => Exceptions::AccountMissingPaymentMethodException,
    31 => Exceptions::AccountPaymentRequiredException,
    32 => Exceptions::AccountBannedException,
    33 => Exceptions::AccountDisabledException,
    39 => Exceptions::InsertInvalidRangeException,
    # Column errors (40 - 59)
    40 => Exceptions::ColumnMissingParamException,
    41 => Exceptions::ColumnTypeException,
    42 => Exceptions::ColumnIntegerValuesException,
    43 => Exceptions::ColumnAlreadyExistsException,
    44 => Exceptions::ColumnLimitException,
    45 => Exceptions::ColumnTimeSeriesLimitException,
    46 => Exceptions::ColumnTimeSeriesSystemLimitException,
    47 => Exceptions::ColumnDecimalTypeException,
    48 => Exceptions::ColumnStorageValueException,
    49 => Exceptions::ColumnInvalidApiNameException,
    50 => Exceptions::ColumnInvalidNameException,
    51 => Exceptions::ColumnInvalidDescriptionException,
    52 => Exceptions::ColumnExceededDescriptionlengthException,
    53 => Exceptions::ColumnInvalidCardinalityException,
    54 => Exceptions::ColumnDecimalLimitException,
    55 => Exceptions::ColumnRangeLimitException,
    55 => Exceptions::ColumnExceededMaxNameLenghtException,
    55 => Exceptions::ColumnExceededMaxApiNameLenghtException,
    55 => Exceptions::ColumnEmptyEntityIdException,
    55 => Exceptions::ColumnExceededPermitedValueException,
    # Insert errors (60 - 79)
    60 => Exceptions::InsertInvalidDecimalPlacesException,
    61 => Exceptions::InsertEntityValueTypeException,
    62 => Exceptions::InsertColumnNameTypeException,
    63 => Exceptions::InsertColumnTypeException,
    64 => Exceptions::InsertEntityNameTooBigException,
    65 => Exceptions::InsertColumnValueTooBigException,
    66 => Exceptions::InsertTimeSeriesDateFormatException,
    67 => Exceptions::InsertColumnNotActiveException,
    68 => Exceptions::InsertIdLimitException,
    69 => Exceptions::InsertColumnLimitException,
    70 => Exceptions::InsertDateFormatException,
    71 => Exceptions::InsertColumnStringEmptyValueException,
    72 => Exceptions::InsertColumnTimeSeriesInvalidParameterException,
    73 => Exceptions::InsertColumnNumericInvalidValueException,
    74 => Exceptions::InsertColumnTimeSeriesMissingValueException,
    75 => Exceptions::QueryTimeSeriesInvalidPrecisionSecondsException,
    76 => Exceptions::QueryTimeSeriesInvalidPrecisionMinutesException,
    77 => Exceptions::QueryTimeSeriesInvalidPrecisionHoursException,
    78 => Exceptions::QueryDateFormatException,
    79 => Exceptions::QueryRelativeIntervalException,
    # Query errors (80 - 109)
    80 => Exceptions::QueryMissingQueryException,
    81 => Exceptions::QueryInvalidTypeException,
    82 => Exceptions::QueryMissingTypeParamException,
    83 => Exceptions::QueryInvalidOperatorException,
    84 => Exceptions::QueryIncorrectOperatorUsageException,
    85 => Exceptions::QueryColumnNotActiveException,
    86 => Exceptions::QueryMissingOperatorException,
    87 => Exceptions::QueryIncompleteException,
    88 => Exceptions::QueryEventCountQueryException,
    89 => Exceptions::QueryInvalidMetricException,
    90 => Exceptions::QueryIntegerException,
    91 => Exceptions::QueryColumnLimitException,
    92 => Exceptions::QueryLevelLimitException,
    93 => Exceptions::QueryBadAggsFormationException,
    94 => Exceptions::QueryInvalidAggFilterException,
    95 => Exceptions::QueryMetricsLevelException,
    96 => Exceptions::QueryTimeSeriesException,
    97 => Exceptions::QueryMetricsTypeException,
    98 => Exceptions::QueryContainsNumericException,
    99 => Exceptions::QueryExistsEntityLimitException,
    100 => Exceptions::QueryMultipleFiltersException,
    102 => Exceptions::QueryMissingNameParamException,
    103 => Exceptions::QuerySavedAlreadyExistsException,
    104 => Exceptions::QuerySavedNotExistsException,
    105 => Exceptions::QuerySavedInvalidTypeException,
    106 => Exceptions::MethodNotAllowedException,
    107 => Exceptions::QueryExistsMissingIdsException,
    108 => Exceptions::QueryInvalidFormatException,
    109 => Exceptions::QueryTopValuesParameterEmptyException,
    110 => Exceptions::QueryDataExtractionLimitValueException,
    111 => Exceptions::QueryDataExtractionLimitValueTooBigException,
    112 => Exceptions::QueryDataExtractionLimitAndPageTokenValueException,
    113 => Exceptions::QueryDataExtractionPageTokenValueException,
    114 => Exceptions::QueryDataExtractionColumnLimitException,
    115 => Exceptions::QueryExistsEntityEmptyException,
    116 => Exceptions::QuerySavedInvalidQueryValueException,
    117 => Exceptions::QuerySavedInvalidCachePeriodValueException,
    118 => Exceptions::QuerySavedInvalidNameException,
    119 => Exceptions::QueryCountInvalidParameterErrorException,
    120 => Exceptions::QueryAggregationInvalidParameterException,
    121 => Exceptions::QueryAggregationInvalidFilterQueryException,
    122 => Exceptions::QueryInvalidMinfreqException,
    123 => Exceptions::QueryExceededMaxNumberQuerysException,
    124 => Exceptions::QueryInvalidOperatorUsageException,
    125 => Exceptions::QueryInvalidParameterUsageException,
    126 => Exceptions::QueryParameterInvalidColumnUsageException,
    127 => Exceptions::QueryInvalidColumnUsageException,
    # Internal errors (110 - 120)
    130 => Exceptions::InternalServerException,
    131 => Exceptions::ColumnCreateInternalException
}
end
